#!/bin/sh

# No point in proceeding if netconfig is not enabled.
if ! systemctl is-enabled netconfig.service &> /dev/null; then
  exit 0
fi

case $1 in
stop)
  /bin/systemctl stop netconfig.service
  ;;
start)
  /usr/bin/sleep 5
  /bin/systemctl start netconfig.service
  ;;
esac

exit 0
