.TH frugalwareutils 3 "2 May 2006" "Frugalware 0.5" ""
.SH NAME
frugalwareutils \- Developer documentation for the Frugalware configuration
libraries
.SH SYNOPSIS
For ease of access, the frugalwareutils manual has been split up into several
sections.

.nf
libfwdialog         Functions to make libdialog usage easier.
libfwnetconfig      Functions to make network configuration easier.
libfwtimeconfig     Functions to make time configuration easier.
libfwutil           Functions to make writing Frugalware configuration tools
                    easier.
.fi

.SH AUTHORS
Written by Miklos Vajna.
.SH "REPORTING BUGS"
If you find any bug, then please file a bugreport at <http://bugs.frugalware.org/>.
