.TH frugalwareutils 3 "17 Jun 2006" "Frugalware 0.5" ""
.SH NAME
frugalwareutils \- Developer documentation for the Frugalware configuration
libraries
.SH SYNOPSIS
For ease of access, the frugalwareutils manual has been split up into several
sections.

.nf
SUBDIRS = doc libfwutil libfwdialog setup \
          libfwnetconfig netconfig \
          libfwtimeconfig timeconfig \
          libfwraidconfig raidconfig \
          libfwmouseconfig mouseconfig \
          libfwxconfig

libfwutil           Functions to make writing Frugalware configuration tools
                    easier.
libfwdialog         Functions to make libdialog usage easier.
libfwnetconfig      Functions to make network configuration easier.
libfwtimeconfig     Functions to make time configuration easier.
libfwraidconfig     Functions to make RAID configuration easier.
libfwmouseconfig    Functions to make mouse configuration easier.
libfwxonfig         Functions to make X configuration easier.
libfwgrubonfig      Functions to make GRUB configuration easier.
.fi

.SH AUTHORS
Written by Miklos Vajna.
.SH "REPORTING BUGS"
If you find any bug, then please file a bugreport at <http://bugs.frugalware.org/>.
